version: "2"
run:
  timeout: 5m
  concurrency: 4
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unparam
    - zerologlint
  disable:
    - prealloc
  settings:
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
    funlen:
      lines: 60
      statements: 40
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    gocyclo:
      min-complexity: 10
    gosec:
      excludes: []
    govet:
      enable:
        - atomicalign
      disable:
        - shadow
      enable-all: false
      disable-all: false
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Fatalf
    lll:
      line-length: 120
      tab-width: 1
    misspell:
      locale: US
      ignore-rules:
        - aftership
        - automizely
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - path: _test\.go
        linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
